# Generated by Django 4.0 on 2021-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(upload_to='news_thumbnail/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(upload_to='news_video/'),
        ),
    ]
